version: '3.3'

services:
  db:
    image: dimaxdqwerty/db-shop:latest
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=shop
    ports:
      - "5432:5432"
    container_name: db-shop
