version: '3.3'

services:
  db:
    build:
      context: ./docker
      dockerfile: db/Dockerfile
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=shop
    ports:
      - "5432:5432"
    container_name: db-shop
